spring:
  application:
    name: assignment
  datasource:
    url: jdbc:mysql://localhost:3306/zorvyn
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8081


security:
  secret-key: "1d84793e9ba52b3309f63c16e03c8fd6b26dcfcf915738fffe1843ddbb56db21"