spring:
  application:
    name: assignment
  datasource:
    url: jdbc:mysql://localhost:3306/zorvyn
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8081


security:
  secret-key: "mySuperSecretKeyThatIsAtLeast32CharactersLong"